/**
 * @file: dmusic-resources.ts
 * @description: dmusic-resources.ts description
 * @author: YanYuCloudCube Team
 * @version: v1.0.0
 * @created: 2026-04-07
 * @updated: 2026-04-07
 * @status: active
 * @tags: [type]
 */

export interface MusicTrack {
  id: string;
  title: string;
  artist: string;
  album: string;
  duration: number;
  audioUrl: string;
  coverUrl?: string;
  videoUrl?: string;
  emotion: 'happy' | 'sad' | 'energetic' | 'calm' | 'love' | 'neutral';
  genre: string;
  year?: number;
  lyrics?: string[];
}

export interface Album {
  id: string;
  name: string;
  coverUrl?: string;
  tracks: MusicTrack[];
  description?: string;
}

export interface ArtistProfile {
  id: string;
  name: string;
  avatarUrl: string;
  bio?: string;
  albums: Album[];
}

export const DMUSIC_LOGOS: string[] = [
  '/D-Music/D-logo/D-logo-20.png',
  '/D-Music/D-logo/D-logo-21.png',
  '/D-Music/D-logo/D-logo-22.png',
  '/D-Music/D-logo/D-logo-23.png',
  '/D-Music/D-logo/D-logo-24.png',
  '/D-Music/D-logo/D-logo-25.png',
  '/D-Music/D-logo/D-logo-26.png',
  '/D-Music/D-logo/D-logo-27.png',
  '/D-Music/D-logo/D-logo-28.png',
  '/D-Music/D-logo/D-logo-29.png',
  '/D-Music/D-logo/D-logo-31.png',
  '/D-Music/D-logo/D-logo-32.png',
  '/D-Music/D-logo/D-logo-33.png',
  '/D-Music/D-logo/D-logo-34.png',
  '/D-Music/D-logo/D-logo-35.png',
  '/D-Music/D-logo/D-logo-36.png',
  '/D-Music/D-logo/D-logo-37.png',
  '/D-Music/D-logo/D-logo-38.png',
  '/D-Music/D-logo/D-logo-39.png',
  '/D-Music/D-logo/D-logo-49.png',
  '/D-Music/D-logo/D-logo-50.png',
  '/D-Music/D-logo/D-logo-51.png',
  '/D-Music/D-logo/D-logo-52.png',
  '/D-Music/D-logo/D-logo-53.png',
  '/D-Music/D-logo/D-logo-54.png',
  '/D-Music/D-logo/D-logo-55.png',
  '/D-Music/D-logo/D-logo-56.png',
  '/D-Music/D-logo/D-logo-57.png',
  '/D-Music/D-logo/D-logo-58.png',
  '/D-Music/D-logo/D-logo-59.png',
];

export const DMUSIC_PHOTOS: string[] = [
  '/D-Music/D-98/Music-1978.jpg',
  '/D-Music/D-98/Music-1979.jpg',
  '/D-Music/D-98/Music-1980.jpg',
  '/D-Music/D-98/Music-1981.jpg',
  '/D-Music/D-98/Music-1982.jpg',
  '/D-Music/D-98/Music-1983.jpg',
  '/D-Music/D-98/Music-1990.jpg',
  '/D-Music/D-98/Music-1991.jpg',
  '/D-Music/D-98/Music-1992.jpg',
  '/D-Music/D-98/Music-1993.jpg',
  '/D-Music/D-98/Music-1994.jpg',
  '/D-Music/D-98/Music-1995.jpg',
  '/D-Music/D-98/Music-1996.jpg',
  '/D-Music/D-98/Music-1997.jpg',
];

export const DMUSIC_VIDEOS: string[] = [
  '/D-Music/D-98-Mp4/Music-1989.mp4',
  '/D-Music/D-98-Mp4/Music-1990.mp4',
  '/D-Music/D-98-Mp4/Music-1991.mp4',
  '/D-Music/D-98-Mp4/Music-1992.mp4',
  '/D-Music/D-98-Mp4/Music-1993.mp4',
  '/D-Music/D-98-Mp4/Music-1994.mp4',
  '/D-Music/D-98-Mp4/Music-1995.mp4',
];

export const MUSIC_LIBRARY: MusicTrack[] = [
  {
    id: 'music-a-01',
    title: '那些年',
    artist: '董小姐',
    album: 'Music-A',
    duration: 240,
    audioUrl: '/Music-Mp3/Music-A/那些年.mp3',
    coverUrl: '/D-Music/D-98/Music-1978.jpg',
    videoUrl: '/D-Music/D-98-Mp4/Music-1989.mp4',
    emotion: 'sad',
    genre: '流行',
    year: 2024,
  },
  {
    id: 'music-a-02',
    title: '冬月里的生命之花',
    artist: '董小姐',
    album: 'Music-A',
    duration: 220,
    audioUrl: '/Music-Mp3/Music-A/冬月里的生命之花.mp3',
    coverUrl: '/D-Music/D-98/Music-1979.jpg',
    videoUrl: '/D-Music/D-98-Mp4/Music-1990.mp4',
    emotion: 'calm',
    genre: '抒情',
    year: 2024,
  },
  {
    id: 'music-a-03',
    title: '不过时间而已',
    artist: '董小姐',
    album: 'Music-A',
    duration: 200,
    audioUrl: '/Music-Mp3/Music-A/不过时间而已.mp3',
    coverUrl: '/D-Music/D-98/Music-1980.jpg',
    emotion: 'sad',
    genre: '流行',
    year: 2024,
  },
  {
    id: 'music-a-04',
    title: '如梦的岁月',
    artist: '董小姐',
    album: 'Music-A',
    duration: 230,
    audioUrl: '/Music-Mp3/Music-A/如梦的岁月.mp3',
    coverUrl: '/D-Music/D-98/Music-1981.jpg',
    videoUrl: '/D-Music/D-98-Mp4/Music-1991.mp4',
    emotion: 'calm',
    genre: '抒情',
    year: 2024,
  },
  {
    id: 'music-a-05',
    title: '那如梦的岁月',
    artist: '董小姐',
    album: 'Music-A',
    duration: 215,
    audioUrl: '/Music-Mp3/Music-A/那如梦的岁月.mp3',
    coverUrl: '/D-Music/D-98/Music-1982.jpg',
    videoUrl: '/D-Music/D-98-Mp4/Music-1992.mp4',
    emotion: 'calm',
    genre: '抒情',
    year: 2024,
  },
  {
    id: 'music-a-06',
    title: '岁月中丢失了年岁',
    artist: '董小姐',
    album: 'Music-A',
    duration: 225,
    audioUrl: '/Music-Mp3/Music-A/岁月中丢失了年岁.mp3',
    coverUrl: '/D-Music/D-98/Music-1983.jpg',
    videoUrl: '/D-Music/D-98-Mp4/Music-1993.mp4',
    emotion: 'sad',
    genre: '流行',
    year: 2024,
  },
  {
    id: 'music-a-07',
    title: '一生一世的爱与陪伴',
    artist: '董小姐',
    album: 'Music-A',
    duration: 260,
    audioUrl: '/Music-Mp3/Music-A/一生一世的爱与陪伴.mp3',
    coverUrl: '/D-Music/D-98/Music-1990.jpg',
    videoUrl: '/D-Music/D-98-Mp4/Music-1994.mp4',
    emotion: 'love',
    genre: '抒情',
    year: 2024,
  },
  {
    id: 'music-a-08',
    title: '是你把自己弄丢了',
    artist: '董小姐',
    album: 'Music-A',
    duration: 210,
    audioUrl: '/Music-Mp3/Music-A/是你把自己弄丢了.mp3',
    coverUrl: '/D-Music/D-98/Music-1991.jpg',
    emotion: 'sad',
    genre: '流行',
    year: 2024,
  },
  {
    id: 'music-a-09',
    title: '冬月里的季风',
    artist: '董小姐',
    album: 'Music-A',
    duration: 195,
    audioUrl: '/Music-Mp3/Music-A/冬月里的季风.mp3',
    coverUrl: '/D-Music/D-98/Music-1992.jpg',
    emotion: 'calm',
    genre: '抒情',
    year: 2024,
  },
  {
    id: 'music-a-10',
    title: '冬日里温暖的季风拂过她的脸',
    artist: '董小姐',
    album: 'Music-A',
    duration: 245,
    audioUrl: '/Music-Mp3/Music-A/冬日里温暖的季风拂过她的脸.mp3',
    coverUrl: '/D-Music/D-98/Music-1993.jpg',
    emotion: 'calm',
    genre: '抒情',
    year: 2024,
  },
  {
    id: 'music-a-11',
    title: '彼岸花的宿命',
    artist: '董小姐',
    album: 'Music-A',
    duration: 235,
    audioUrl: '/Music-Mp3/Music-A/彼岸花的宿命.mp3',
    coverUrl: '/D-Music/D-98/Music-1994.jpg',
    emotion: 'sad',
    genre: '古风',
    year: 2024,
  },
  {
    id: 'music-a-12',
    title: '雨季标本',
    artist: '董小姐',
    album: 'Music-A',
    duration: 205,
    audioUrl: '/Music-Mp3/Music-A/雨季标本.mp3',
    coverUrl: '/D-Music/D-98/Music-1995.jpg',
    emotion: 'sad',
    genre: '流行',
    year: 2024,
  },
  {
    id: 'music-a-13',
    title: '未曾守护的梦',
    artist: '董小姐',
    album: 'Music-A',
    duration: 220,
    audioUrl: '/Music-Mp3/Music-A/未曾守护的梦.mp3',
    coverUrl: '/D-Music/D-98/Music-1996.jpg',
    emotion: 'sad',
    genre: '抒情',
    year: 2024,
  },
  {
    id: 'music-a-14',
    title: '辗转反侧的梦',
    artist: '董小姐',
    album: 'Music-A',
    duration: 190,
    audioUrl: '/Music-Mp3/Music-A/辗转反侧的梦.mp3',
    coverUrl: '/D-Music/D-98/Music-1997.jpg',
    emotion: 'sad',
    genre: '流行',
    year: 2024,
  },
  {
    id: 'music-b-01',
    title: '七秒之外',
    artist: '董小姐',
    album: 'Music-B',
    duration: 210,
    audioUrl: '/Music-Mp3/Music-B/七秒之外.mp3',
    coverUrl: '/D-Music/D-logo/D-logo-20.png',
    emotion: 'energetic',
    genre: '摇滚',
    year: 2024,
  },
  {
    id: 'music-b-02',
    title: '不过时间而已',
    artist: '董小姐',
    album: 'Music-B',
    duration: 200,
    audioUrl: '/Music-Mp3/Music-B/不过时间而已.mp3',
    coverUrl: '/D-Music/D-logo/D-logo-21.png',
    emotion: 'sad',
    genre: '流行',
    year: 2024,
  },
  {
    id: 'music-b-03',
    title: '冬日暖阳',
    artist: '董小姐',
    album: 'Music-B',
    duration: 230,
    audioUrl: '/Music-Mp3/Music-B/冬日暖阳.mp3',
    coverUrl: '/D-Music/D-logo/D-logo-22.png',
    emotion: 'happy',
    genre: '抒情',
    year: 2024,
  },
  {
    id: 'music-b-04',
    title: '逐梦之路',
    artist: '董小姐',
    album: 'Music-B',
    duration: 240,
    audioUrl: '/Music-Mp3/Music-B/逐梦之路.mp3',
    coverUrl: '/D-Music/D-logo/D-logo-23.png',
    emotion: 'energetic',
    genre: '励志',
    year: 2024,
  },
  {
    id: 'music-b-05',
    title: '浮生似梦',
    artist: '董小姐',
    album: 'Music-B',
    duration: 215,
    audioUrl: '/Music-Mp3/Music-B/浮生似梦.mp3',
    coverUrl: '/D-Music/D-logo/D-logo-24.png',
    emotion: 'calm',
    genre: '古风',
    year: 2024,
  },
  {
    id: 'music-b-06',
    title: '奈何彼岸花',
    artist: '董小姐',
    album: 'Music-B',
    duration: 225,
    audioUrl: '/Music-Mp3/Music-B/奈何彼岸花.mp3',
    coverUrl: '/D-Music/D-logo/D-logo-25.png',
    emotion: 'sad',
    genre: '古风',
    year: 2024,
  },
  {
    id: 'music-b-07',
    title: '岁月如歌',
    artist: '董小姐',
    album: 'Music-B',
    duration: 235,
    audioUrl: '/Music-Mp3/Music-B/岁月如歌.mp3',
    coverUrl: '/D-Music/D-logo/D-logo-26.png',
    emotion: 'calm',
    genre: '流行',
    year: 2024,
  },
  {
    id: 'music-b-08',
    title: '只如初见若',
    artist: '董小姐',
    album: 'Music-B',
    duration: 205,
    audioUrl: '/Music-Mp3/Music-B/只如初见若.mp3',
    coverUrl: '/D-Music/D-logo/D-logo-27.png',
    emotion: 'love',
    genre: '抒情',
    year: 2024,
  },
  {
    id: 'music-b-09',
    title: '浮生如渡',
    artist: '董小姐',
    album: 'Music-B',
    duration: 220,
    audioUrl: '/Music-Mp3/Music-B/浮生如渡.mp3',
    coverUrl: '/D-Music/D-logo/D-logo-28.png',
    emotion: 'calm',
    genre: '古风',
    year: 2024,
  },
  {
    id: 'music-b-10',
    title: '雨幕独白',
    artist: '董小姐',
    album: 'Music-B',
    duration: 195,
    audioUrl: '/Music-Mp3/Music-B/雨幕独白.mp3',
    coverUrl: '/D-Music/D-logo/D-logo-29.png',
    emotion: 'sad',
    genre: '流行',
    year: 2024,
  },
  {
    id: 'music-b-11',
    title: '黎明的梦',
    artist: '董小姐',
    album: 'Music-B',
    duration: 210,
    audioUrl: '/Music-Mp3/Music-B/黎明的梦.mp3',
    coverUrl: '/D-Music/D-logo/D-logo-31.png',
    emotion: 'calm',
    genre: '抒情',
    year: 2024,
  },
  {
    id: 'music-b-12',
    title: '董小姐的祝福',
    artist: '董小姐',
    album: 'Music-B',
    duration: 180,
    audioUrl: '/Music-Mp3/Music-B/董小姐的祝福.wav',
    coverUrl: '/D-Music/D-logo/D-logo-32.png',
    emotion: 'happy',
    genre: '祝福',
    year: 2024,
  },
  {
    id: 'music-c-01',
    title: '那些年',
    artist: '董小姐',
    album: 'Music-C',
    duration: 240,
    audioUrl: '/Music-Mp3/Music-C/那些年.mp3',
    coverUrl: '/D-Music/D-logo/D-logo-33.png',
    emotion: 'sad',
    genre: '流行',
    year: 2024,
  },
  {
    id: 'music-c-02',
    title: '不过时间而已',
    artist: '董小姐',
    album: 'Music-C',
    duration: 200,
    audioUrl: '/Music-Mp3/Music-C/不过时间而已.mp3',
    coverUrl: '/D-Music/D-logo/D-logo-34.png',
    emotion: 'sad',
    genre: '流行',
    year: 2024,
  },
  {
    id: 'music-c-03',
    title: '若只如初见',
    artist: '董小姐',
    album: 'Music-C',
    duration: 215,
    audioUrl: '/Music-Mp3/Music-C/若只如初见.mp3',
    coverUrl: '/D-Music/D-logo/D-logo-35.png',
    emotion: 'love',
    genre: '抒情',
    year: 2024,
  },
  {
    id: 'music-c-04',
    title: '若善良真的已消失不见',
    artist: '董小姐',
    album: 'Music-C',
    duration: 230,
    audioUrl: '/Music-Mp3/Music-C/若善良真的已消失不见.mp3',
    coverUrl: '/D-Music/D-logo/D-logo-36.png',
    emotion: 'sad',
    genre: '流行',
    year: 2024,
  },
  {
    id: 'music-c-05',
    title: '热血摇滚',
    artist: '董小姐',
    album: 'Music-C',
    duration: 195,
    audioUrl: '/Music-Mp3/Music-C/热血摇滚.mp3',
    coverUrl: '/D-Music/D-logo/D-logo-37.png',
    emotion: 'energetic',
    genre: '摇滚',
    year: 2024,
  },
  {
    id: 'music-c-06',
    title: '男人的难',
    artist: '董小姐',
    album: 'Music-C',
    duration: 250,
    audioUrl: '/Music-Mp3/Music-C/男人的难.mp3',
    coverUrl: '/D-Music/D-logo/D-logo-38.png',
    emotion: 'sad',
    genre: '流行',
    year: 2024,
  },
  {
    id: 'music-c-07',
    title: '未曾守护的梦',
    artist: '董小姐',
    album: 'Music-C',
    duration: 220,
    audioUrl: '/Music-Mp3/Music-C/未曾守护的梦.mp3',
    coverUrl: '/D-Music/D-logo/D-logo-39.png',
    emotion: 'sad',
    genre: '抒情',
    year: 2024,
  },
  {
    id: 'music-c-08',
    title: '七秒之外',
    artist: '董小姐',
    album: 'Music-C',
    duration: 210,
    audioUrl: '/Music-Mp3/Music-C/七秒之外.mp3',
    coverUrl: '/D-Music/D-logo/D-logo-49.png',
    emotion: 'energetic',
    genre: '摇滚',
    year: 2024,
  },
  {
    id: 'music-c-09',
    title: '若善良已不见',
    artist: '董小姐',
    album: 'Music-C',
    duration: 225,
    audioUrl: '/Music-Mp3/Music-C/若善良已不见.mp3',
    coverUrl: '/D-Music/D-logo/D-logo-50.png',
    emotion: 'sad',
    genre: '流行',
    year: 2024,
  },
  {
    id: 'music-c-10',
    title: '一次就好',
    artist: '董小姐',
    album: 'Music-C',
    duration: 205,
    audioUrl: '/Music-Mp3/Music-C/一次就好.mp3',
    coverUrl: '/D-Music/D-logo/D-logo-51.png',
    emotion: 'love',
    genre: '抒情',
    year: 2024,
  },
  {
    id: 'music-c-11',
    title: '撕碎星空的扉页',
    artist: '董小姐',
    album: 'Music-C',
    duration: 235,
    audioUrl: '/Music-Mp3/Music-C/撕碎星空的扉页.mp3',
    coverUrl: '/D-Music/D-logo/D-logo-52.png',
    emotion: 'energetic',
    genre: '摇滚',
    year: 2024,
  },
  {
    id: 'music-c-12',
    title: '河洛情韵',
    artist: '董小姐',
    album: 'Music-C',
    duration: 245,
    audioUrl: '/Music-Mp3/Music-C/河洛情韵.mp3',
    coverUrl: '/D-Music/D-logo/D-logo-53.png',
    emotion: 'calm',
    genre: '古风',
    year: 2024,
  },
  {
    id: 'music-d-01',
    title: '那些年',
    artist: '董小姐',
    album: 'Music-D',
    duration: 240,
    audioUrl: '/Music-Mp3/Music-D/那些年.mp3',
    coverUrl: '/D-Music/D-logo/D-logo-54.png',
    emotion: 'sad',
    genre: '流行',
    year: 2024,
  },
  {
    id: 'music-d-02',
    title: '不过时间而已',
    artist: '董小姐',
    album: 'Music-D',
    duration: 200,
    audioUrl: '/Music-Mp3/Music-D/不过时间而已.mp3',
    coverUrl: '/D-Music/D-logo/D-logo-55.png',
    emotion: 'sad',
    genre: '流行',
    year: 2024,
  },
  {
    id: 'music-d-03',
    title: '若只如初见',
    artist: '董小姐',
    album: 'Music-D',
    duration: 215,
    audioUrl: '/Music-Mp3/Music-D/若只如初见.mp3',
    coverUrl: '/D-Music/D-logo/D-logo-56.png',
    emotion: 'love',
    genre: '抒情',
    year: 2024,
  },
  {
    id: 'music-d-04',
    title: '若善良真的已消失不见',
    artist: '董小姐',
    album: 'Music-D',
    duration: 230,
    audioUrl: '/Music-Mp3/Music-D/若善良真的已消失不见.mp3',
    coverUrl: '/D-Music/D-logo/D-logo-57.png',
    emotion: 'sad',
    genre: '流行',
    year: 2024,
  },
  {
    id: 'music-d-05',
    title: '不懂的董小姐',
    artist: '董小姐',
    album: 'Music-D',
    duration: 220,
    audioUrl: '/Music-Mp3/Music-D/不懂的董小姐.mp3',
    coverUrl: '/D-Music/D-logo/D-logo-58.png',
    emotion: 'sad',
    genre: '流行',
    year: 2024,
  },
  {
    id: 'music-d-06',
    title: '热血摇滚',
    artist: '董小姐',
    album: 'Music-D',
    duration: 195,
    audioUrl: '/Music-Mp3/Music-D/热血摇滚.mp3',
    coverUrl: '/D-Music/D-logo/D-logo-59.png',
    emotion: 'energetic',
    genre: '摇滚',
    year: 2024,
  },
  {
    id: 'music-d-07',
    title: '男人的难',
    artist: '董小姐',
    album: 'Music-D',
    duration: 250,
    audioUrl: '/Music-Mp3/Music-D/男人的难.mp3',
    coverUrl: '/D-Music/D-98/Music-1978.jpg',
    emotion: 'sad',
    genre: '流行',
    year: 2024,
  },
  {
    id: 'music-d-08',
    title: '若善良已不见',
    artist: '董小姐',
    album: 'Music-D',
    duration: 225,
    audioUrl: '/Music-Mp3/Music-D/若善良已不见.mp3',
    coverUrl: '/D-Music/D-98/Music-1979.jpg',
    emotion: 'sad',
    genre: '流行',
    year: 2024,
  },
  {
    id: 'music-d-09',
    title: '一次就好',
    artist: '董小姐',
    album: 'Music-D',
    duration: 205,
    audioUrl: '/Music-Mp3/Music-D/一次就好.mp3',
    coverUrl: '/D-Music/D-98/Music-1980.jpg',
    emotion: 'love',
    genre: '抒情',
    year: 2024,
  },
  {
    id: 'music-d-10',
    title: '撕碎星空的扉页',
    artist: '董小姐',
    album: 'Music-D',
    duration: 235,
    audioUrl: '/Music-Mp3/Music-D/撕碎星空的扉页.mp3',
    coverUrl: '/D-Music/D-98/Music-1981.jpg',
    emotion: 'energetic',
    genre: '摇滚',
    year: 2024,
  },
  {
    id: 'music-d-11',
    title: '河洛情韵',
    artist: '董小姐',
    album: 'Music-D',
    duration: 245,
    audioUrl: '/Music-Mp3/Music-D/河洛情韵.mp3',
    coverUrl: '/D-Music/D-98/Music-1982.jpg',
    emotion: 'calm',
    genre: '古风',
    year: 2024,
  },
  {
    id: 'music-d-12',
    title: '98',
    artist: '董小姐',
    album: 'Music-D',
    duration: 210,
    audioUrl: '/Music-Mp3/Music-D/98.mp3',
    coverUrl: '/D-Music/D-98/Music-1983.jpg',
    emotion: 'happy',
    genre: '流行',
    year: 2024,
  },
];

export const ALBUMS: Album[] = [
  {
    id: 'album-a',
    name: 'Music-A',
    coverUrl: '/D-Music/D-98/Music-1978.jpg',
    description: '董小姐原创音乐专辑 A',
    tracks: MUSIC_LIBRARY.filter(t => t.album === 'Music-A'),
  },
  {
    id: 'album-b',
    name: 'Music-B',
    coverUrl: '/D-Music/D-logo/D-logo-20.png',
    description: '董小姐原创音乐专辑 B',
    tracks: MUSIC_LIBRARY.filter(t => t.album === 'Music-B'),
  },
  {
    id: 'album-c',
    name: 'Music-C',
    coverUrl: '/D-Music/D-logo/D-logo-33.png',
    description: '董小姐原创音乐专辑 C',
    tracks: MUSIC_LIBRARY.filter(t => t.album === 'Music-C'),
  },
  {
    id: 'album-d',
    name: 'Music-D',
    coverUrl: '/D-Music/D-98/Music-1990.jpg',
    description: '董小姐原创音乐专辑 D',
    tracks: MUSIC_LIBRARY.filter(t => t.album === 'Music-D'),
  },
];

export const ARTIST_PROFILE: ArtistProfile = {
  id: 'artist-dong',
  name: '董小姐',
  avatarUrl: '/D-Music/D-logo/D-logo-20.png',
  bio: '独立音乐人，原创歌手',
  albums: ALBUMS,
};

export function getRandomLogo(): string {
  return DMUSIC_LOGOS[Math.floor(Math.random() * DMUSIC_LOGOS.length)];
}

export function getRandomPhoto(): string {
  return DMUSIC_PHOTOS[Math.floor(Math.random() * DMUSIC_PHOTOS.length)];
}

export function getTracksByEmotion(emotion: MusicTrack['emotion']): MusicTrack[] {
  return MUSIC_LIBRARY.filter(t => t.emotion === emotion);
}

export function getTracksByAlbum(album: string): MusicTrack[] {
  return MUSIC_LIBRARY.filter(t => t.album === album);
}

export function searchTracks(query: string): MusicTrack[] {
  const q = query.toLowerCase();
  return MUSIC_LIBRARY.filter(t => 
    t.title.toLowerCase().includes(q) ||
    t.artist.toLowerCase().includes(q) ||
    t.album.toLowerCase().includes(q) ||
    t.genre.toLowerCase().includes(q)
  );
}
